# This is a sample aws-auth-patch.yml file. 
# Actual aws-auth-patch.yml will be created at /tmp/aws-auth-patch.yml path.
# Replace <ACCOUNT_ID> with your AWS account Id.

apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::<ACCOUNT_ID>:role/UdacityFlaskDeployCBKubectlRole
      username: build      
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::<ACCOUNT_ID>:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-17C402QC9VF6L
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-02-26T07:40:38Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "5992"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 5bf363cb-504c-4289-93ce-74257aff0de4
